services:
  - type: web
    name: aimdoc-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /health
